### ISSUE TITLE
"No such file ..." error on run-groovy command

### ISSUE THREAD

**Issue by abhi18av** [Groovy-Emacs-Modes/groovy-emacs-modes#31] opened 2016-11-16 14:08 UTC
Hi @russel 

I wish to use the `groovy-mode` and I've installed it from MELPA via package manager. Syntax-highlight etc are working fine but when I do `run-groovy` command the `inferior groovy` buffer opens up and throws the error 
` No such file or directory `

I've have checked that the `groovysh` etc commands are working fine. I used  ` brew install groovy` for the installation. Is this a path config error, how to correct it?

**Comment by abhi18av** [comment] 2016-11-16 14:16
I've tried out the suggestions in #30 without any success.

**Comment by russel** [comment] 2016-11-16 15:09
On the one hand I can be smug – it works for me. On the other hand we need to make it work for you.

The problem with the error message `No such file or directory` it is not clear which file is being sought. If groovysh is on you PATH then perhaps the problem is that the file inf-groovy.el is not in the same directory as groovy-mode.el?

**Comment by abhi18av** [comment] 2016-11-16 15:39
No, that's not the case since it's all in the `~/.emacs.d/elpa/groovy-mode/` so that's not an issue. Still, I do notice that when the `inferior-groovy` shell pops up, it's initial directory is in emacs(?) which is something new for me. Normally, the directory path is set to the current directory

**Comment by russel** [comment] 2016-11-16 17:14
The only file path I can see with a quick look is the path to groovy and groovysh. The assumption is $GROOVY_HOME/bin/{groovy,groovysh} (with a .bat extension on Windows).

**Comment by abhi18av** [comment] 2016-11-16 18:01
Yeah, but do I still need to set it explicitly even if the `groovysh` command works. Please let me know if there's some shell-magic involved :)

**Comment by abhi18av** [comment] 2016-11-17 08:25
Okay, so I've made some progress. I just reinstalled  `groovy` using `sdkman` and this time `echo $GROOVY_HOME` does print out the home directory. 

But, the the problem is still the same in emacs `inferior groovy shell`. What's your say @russel ?

**Comment by russel** [comment] 2017-05-16 08:46
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.

**Closed by russel** 2017-05-16 08:46 UTC
