### ISSUE TITLE
Incorrect highlighting if literal string include comment like strings

### ISSUE THREAD

**Issue by MarkSymsCtx** [Groovy-Emacs-Modes/groovy-emacs-modes#32] opened 2017-02-07 15:43 UTC
If there are literal string in the Groovy script that look like comments then the syntax highlighting goes wrong.

e.g

"https://myartifactoryserver.company.net/api/copy/"
or "pattern": "${src}/*",

In the first example the syntax highlighting switches to comment at the // and runs until some higher level terminator triggers and in the second it switches to comment mode at the /* and run until it sees a */ i.e. the end of a later comment.

This not only makes things hard to read but also upsets the indentation system as well.

**Comment by Wilfred** [comment] 2017-03-01 15:29
I can't reproduce this. Could you provide a full code snippet that shows this behaviour?

**Comment by MarkSymsCtx** [comment] 2017-03-01 15:37
Here you go, it's being seen in a method that builds a JSON upload spec for Artifactory (on my machine it goes very obviously wrong at "${src}/*" but looking at it in more detail I think it starts going wrong at "files" - 

def upload(env, buildinfo, server, flat, src, dst) {
  def uploadSpec = """{
    "files": [
      {
       "regexp": "false",
       "flat": "${flat}",
       "pattern": "${src}/*",
       "target": "${dst}/"
      }
    ]
 }"""

...
}

**Comment by Wilfred** [comment] 2017-03-01 16:26
OK, this is a duplicate of #29 by the looks. The problem is the `"""`.

**Comment by MarkSymsCtx** [comment] 2017-03-01 16:28
Looks like it yes.

**Comment by russel** [comment] 2017-03-01 16:45
I am closing this as a duplicate of #29.

**Closed by russel** 2017-03-01 16:45 UTC
