### ISSUE TITLE
Comment handling is broken

### ISSUE THREAD

**Issue by russel** [Groovy-Emacs-Modes/groovy-emacs-modes#51] opened 2017-05-20 08:52 UTC
The font-lock behaviour with comments is wrong. // without a following space is not treated as a comment. // with a following space is.

**Comment by jgrzebyta** [comment] 2017-05-26 14:40
also `/*` is not treated as a comment.

Gentoo mode version: 20170516.1155
Emacs: 25.1.1

Attached screenshot:

![gentoo_file](https://cloud.githubusercontent.com/assets/6738268/26499210/a9531c6a-4229-11e7-8999-eb197a843124.png)

**Comment by russel** [comment] 2017-05-26 15:55
I think we need @Wilfred to take a look at this if he can.

**Comment by Wilfred** [comment] 2017-05-26 16:27
I cannot replicate either of the issues mentioned.

Given the text:

```groovy
// foo

def x = 1

//bar

def y = 2

/* baz */

def z = 2
```

I'm seeing:

![screen shot 2017-05-26 at 17 27 17](https://cloud.githubusercontent.com/assets/70800/26503444/9c64c7c4-4238-11e7-93ff-5d91c0a510c4.png)

**Comment by Wilfred** [comment] 2017-05-26 16:36
p.s. thanks for pinging me, I would have missed this otherwise.

**Comment by russel** [comment] 2017-05-26 16:58
Try
```
// foo
//

def x = 1

//bar

def y = 2

/* baz */

def z = 2
```

**Comment by Wilfred** [comment] 2017-05-26 17:55
Thanks, I can reproduce. Looks like a bug in `groovy-stringify-slashy-string` which is treating the second `/` in `//` as an opening string delimiter. The comment logic isn't quite right.

**Comment by andreas-marschke** [comment] 2017-06-12 13:05
Theres another issue related to that I think when defining inline Patterns in Groovy
![screen shot 2017-06-12 at 15 02 09](https://user-images.githubusercontent.com/1198936/27035080-501efe48-4f80-11e7-8e72-815d05c6551a.png)

Example code:
```groovy
package com.example.groovy

class ExampleClass {

    private ArrayList<Pattern> _patterns = new ArrayList<Pattern> ([
            ~/.*example-[0-9\.]*\.foo$/
    ])

    public ExampleClass(int num) {
        
    }
}
```

**Comment by vincekd** [comment] 2017-06-28 20:15
Also seeing this, as well as @andreas-marschke's addition.

**Comment by vincekd** [comment] 2017-06-28 22:11
![screenshot from 2017-06-28 18-10-19](https://user-images.githubusercontent.com/641433/27662721-16673288-5c2d-11e7-9e9c-7955d50276ae.png)


Looks like there's a conflict between regular slash-quotes and dollar-sign slash quotes in the problem reported by @andreas-marschke.

I've never dealt with emacs syntax parsing, but I'll look at it tomorrow.

**Comment by grdryn** [comment] 2017-07-17 10:34
I'm not sure if this is related or not (it sounds like it could be): it appears that a single-line comment ending with a question mark will lead to the next line being indented an extra level. E.g.:

```groovy
// Could this be better?
    def x = 1
```

rather than
```groovy
// Could this be better?
def x = 1
```

Using a multi-line quote instead works fine:

```groovy
/* Could this be better? */
def x = 1
```

**Comment by Wilfred** [comment] 2017-07-18 09:34
@grdryn it's not related: this is highlighting, whereas that's indentation.

However, that's a definite bug, which I've fixed in #72.

**Comment by grdryn** [comment] 2017-07-18 10:45
@Wilfred that was quick...thanks a lot! :)

**Comment by vincekd** [comment] 2017-07-20 15:13
Hi @Wilfred, after your fix a `/` for division opens a slashy-string.

**Comment by Wilfred** [comment] 2017-07-21 12:18
Argh, groovy syntax is tricky. I've opened https://stackoverflow.com/questions/45234712/how-does-groovy-distinguish-division-from-strings but it's just not clear to me when Groovy thinks / is a slashy-string delimiter vs when / is divison.

**Comment by vincekd** [comment] 2017-07-21 14:11
Seems tricky. At the very least we know that the slashy string should never go multiple lines (so if there is no termination on that line then it must be division) which it currently does.
![screenshot_20170721_101035](https://user-images.githubusercontent.com/641433/28467162-fd154158-6dfc-11e7-810a-139635e08a54.png)

**Comment by Wilfred** [comment] 2017-07-21 14:27
Slashy-strings can be multiline: http://groovy-lang.org/syntax.html#_slashy_string

I think the correct thing to do is to look at the previous non-whitespace character. If it's `(` or an operator like `=` or `+` it's a slashy-string. Otherwise, it's just division.

**Comment by vincekd** [comment] 2017-07-21 15:08
Yeah, I wrote up this snippet which correctly opens but doesn't correctly close.

``` 
(defconst groovy-slashy-open-regex
    ;; /foo/ is a slashy-string, but // is not.
    (rx
     (or (and bol (0+ space))
         (and
          ;; operators
          (or "+" "-" "=" "+=" "-=" "==" "!="
              "<" "<=" ">" ">=" "&&" "!!" "&" "|" "^" "?" "?:" ":"
              "=~" "==~" "<=>" "<>" "(")
          (0+ space)
          )
         )
     "/"
     (not (any "/"))))
```

**Comment by vincekd** [comment] 2017-07-21 17:54
I played around a bit and got it working, but I have no idea if it's the correct way to do it.

Commit: https://github.com/vincekd/groovy-emacs-modes/commit/d096d15f6d0f85ad94bd820d03de9e2d0650f6e0

![screenshot_20170721_135246](https://user-images.githubusercontent.com/641433/28475843-e5f88966-6e1b-11e7-85cd-cd28c77935a2.png)

**Comment by Wilfred** [comment] 2017-07-24 12:42
I think all the issues raised here have been fixed:

Highlighting:

* `//` without a trailing space
* shebangs
* slashy-strings containing a dollar, `/foo$/`
* division `foo / bar` being confused with slashy-strings

Indentation:

* question marks at the end of comments

Please file separate issues for anything else that crops up.

**Closed by Wilfred** 2017-07-24 12:42 UTC
